# Generated by Django 6.0.6 on 2026-06-16 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'LOGIN'), ('LOGOUT', 'LOGOUT'), ('CREATE_FILE', 'CREATE_FILE'), ('DELETE_FILE', 'DELETE_FILE'), ('MOVE_FILE', 'MOVE_FILE'), ('CREATE_DIRECTORY', 'CREATE_DIRECTORY'), ('DELETE_DIRECTORY', 'DELETE_DIRECTORY'), ('ADD_USER', 'ADD_USER'), ('DELETE_USER', 'DELETE_USER')], max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
