# Generated by Django 6.0.6 on 2026-06-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recyclebin_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recyclebinitem',
            name='original_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recyclebinitem',
            name='parent_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
